---
- hosts: mesos-slave #comment: mesos is the group name we just defined
  become: yes #comment: this operation needs privilege access
  tasks:
    - name: Start mesos agent
      sudo: yes
      shell: /home/cc/mesos-1.2.0/build/bin/mesos-agent.sh --master=129.114.33.4:5050 --work_dir=/var/lib/mesos
  
      




